### ISSUE TITLE
Use user's default browser (or let them pick a browser)

### ISSUE THREAD

**Issue by syropian** [ellenli/up-next#38] opened 2020-05-06 18:04 UTC
I use Brave as my default browser, and noticed it opened my meeting up in Chrome 😅 

If I could choose the browser, that'd be super, as I actually use Firefox for all my Google meetings, because it's the only browser where my webcam doesn't lag 🤔 

Thanks for the great app!

**Comment by ellenli** [comment] 2020-05-13 20:48
Duplicate of #31. Fixed and will be part of the Up Next 1.0 release.

**Closed by ellenli** 2020-05-13 20:48 UTC
