### ISSUE TITLE
Ignore declined events

### ISSUE THREAD

**Issue by gabriellanata** [ellenli/up-next#37] opened 2020-05-01 17:38 UTC
Up next is showing declined events instead of ignoring them. This is annoying when you declined an event that was at the same time as another one but the wrong one shows up.

(happy to actually help solve these small issues if you need some help with development btw)

Love this app! thanks for making it!

**Comment by ellenli** [comment] 2020-05-13 20:48
Duplicate of #12. Fixed and will be part of the Up Next 1.0 release.

**Closed by ellenli** 2020-05-13 20:48 UTC
