### ISSUE TITLE
Calendar selection isn't saved on restart

### ISSUE THREAD

**Issue by jasonperez** [ellenli/up-next#50] opened 2021-01-06 05:19 UTC
When I choose a different calendar to display, the menubar isn't updated. And when I restart the app, my calendar selection is reset to the first in the list (in this case, US Holidays).

https://user-images.githubusercontent.com/133046/103732074-7ff1a480-4f9b-11eb-8294-99ac7144821a.mp4

**Comment by alexbassy** [comment] 2021-01-06 10:39
I have the same issue. Because it sets the calendar to one in which I have no events, I see no events in the app.

Tested by adding an event to my “Travel” calendar, which is the one the app keeps resetting to:

<img src=https://user-images.githubusercontent.com/1243909/103759284-c5ea4f00-5013-11eb-8722-78e9d10dd28d.png width=300 />

Changing the calendar to the one I want in the preferences has no effect. I restart and it’s back to the Travel calendar again.

**Comment by dylanatsmith** [comment] 2021-01-06 12:36
+1 to this issue.

- The app pre-selects a calendar with no events
- Changing the calendar doesn't update the menubar
- Restarting the app resets the calendar selection

I just downloaded from the App Store today.

**Comment by pllgr** [comment] 2021-01-07 14:50
A different issue but also related to restarting my computer.

I paid for the Pro version. Everytime I restart my computer, it forgets I have the Pro and I have to go in and Restore the Purchase and redo all my settings such as what to show when I don't have meetings.

The calendar I selected stays the saved though (unlike the comments above) - I can start a new open issue if this is unrelated. but thought maybe the issue is related to restarting the computer.

**Comment by alexbassy** [comment] 2021-01-11 08:34
I noticed different behaviour today: when I select the subsequent option in the list of calendars, the correct calendar meetings are displayed in the menu bar. When closing preferences, the options are not reset anymore.

**Comment by dylanatsmith** [comment] 2021-01-11 11:00
I can confirm this. The calendar selection doesn't match the events being displayed.

It seems that if I select the calendar name two down from the one I really want, it displays the events for the calendar I want. For example, to get the events from my work email calendar here, I need to select "Events" (a personal calendar I've given that name).

![image](https://user-images.githubusercontent.com/6905903/104172428-27d3fb80-53fc-11eb-996b-dceb47b3dbce.png)

**Comment by ellenli** [comment] 2021-01-12 18:05
Fixed in 1.0.1, now being reviewed by the App Store now so an update should be available in the next day or two. Sorry about the trouble and thank you for your patience!

**Comment by ellenli** [comment] 2021-01-13 20:34
[Update now available.](https://apps.apple.com/us/app/up-next/id1355117041?ls=1&mt=12)

**Closed by ellenli** 2021-01-13 20:34 UTC

**Comment by alexbassy** [comment] 2021-01-14 15:07
Thanks @ellenli! 💯
