### ISSUE TITLE
Shortcut jumps to last meeting even when the menu bar has moved on to the next one

### ISSUE THREAD

**Issue by yahelc** [ellenli/up-next#39] opened 2020-05-13 19:07 UTC
I've noticed that during meeting transition moments, if I hit CMD-J at a moment that the menu bar already has the new current meeting, it occasionally still opens the Google Meet for the last meeting instead. 

(Huge fan of up-next! Thank you for building such a useful tool!)

**Comment by ellenli** [comment] 2020-05-14 20:05
Duplicate of #10 - will be fixed for Up Next 1.0.

**Closed by ellenli** 2020-05-14 20:05 UTC
